services: # docker compose excepts
  # app: # custom key name
  #   build:
  #     context: . # relative path to the build context
  #     dockerfile: Dockerfile # relative path to the Dockerfile
  #   ports:
  #     - "8000:8000" # port mapping - this exposes port 8080 on the host to port 8080 in the container
  #     - "3000:8000" # another port mapping
  #   command: python -m http.server 8000 # command to run

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/Dockerfile
        - action: restart
          path: ./backend/src
        